### GET
GET http://localhost:18070/internalapi/privatepractitioner/all

### POST
POST http://localhost:18070/internalapi/privatepractitioner/validate
Content-Type: application/json

{
  "personalIdentityNumber": "194606109108"
}