### GET
GET http://localhost:18070/internalapi/privatepractitioner/all

### GET
GET http://localhost:18070/internalapi/privatepractitioner?personOrHsaId=192011189228

### GET
GET http://localhost:18070/internalapi/privatepractitioner?personOrHsaId=SE165565594230-WEBCERTBOOT3

### POST
POST http://localhost:18070/internalapi/privatepractitioner/validate
Content-Type: application/json

{
  "personalIdentityNumber": "194606109108"
}

### GET Configuration
GET http://localhost:18070/internalapi/privatepractitioner/configuration

### POST create
POST http://localhost:18070/internalapi/privatepractitioner
Content-Type: application/json

{
  "personId": "201212121212",
  "name": "LillTolvan Tolvansson",
  "position": "202010",
  "careUnitName": "Lilltrollens vårdcentral",
  "ownershipType": "Privat",
  "typeOfCare": "Primärvård",
  "healthcareServiceType": "Vårdcentral",
  "workplaceCode": "arbetsplatskod",
  "phoneNumber": "0123-456789",
  "email": "mail@nisse.se",
  "address": "Addressgatan 1",
  "zipCode": "12345",
  "city": "Stad",
  "municipality": "Kommun",
  "county": "Län",
  "consentFormVersion": 1
}